events { }

http {
    include mime.types;

    types {
        application/wasm wasm;
    }

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html =404;
        }

        location /_framework/ {
            gzip_static on;
            expires max;
            add_header Cache-Control "public, immutable";
        }
        
        location ~* \.(js|css|png|svg|ico|jpg|woff2)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}